baseurl = "https://vlad.gg/"
languageCode = "en-us"
title = "Vlad Zaharia"
theme = ["hugo-cloak-email", "hugo-notice", "vladgg"]

# Automatic menu
sectionPagesMenu = "main"

# Generate robots.txt
enableRobotsTXT = true

# Git integration
enableGitInfo = true

# Emoji integration
enableEmoji = true