baseurl = "https://vlad.gg/"
languageCode = "en-us"
title = "Vlad Zaharia"
theme = ["hugo-cloak-email", "hugo-notice", "vladgg"]

# Menu
sectionPagesMenu = "main"

# Robots.txt
enableRobotsTXT = true

# Git integration
enableGitInfo = true