baseurl = "https://vlad.gg/"
languageCode = "en-us"
theme = ["hugo-cloak-email", "hugo-notice", "vladgg"]
title = "Vlad Zaharia"

# Automatic menu
sectionPagesMenu = "main"

# Generate robots.txt
enableRobotsTXT = true

# Git integration
enableGitInfo = true

# Emoji integration
enableEmoji = true

# Social networks
[[menu.social]]
    identifier = "facebook"
    name = "Facebook"
    post = "primary"
    pre = "facebook-square"
    url = "https://www.facebook.com/vladzaharia/"
    weight = 1

[[menu.social]]
    identifier = "instagram"
    name = "Instagram"
    post = "pink"
    pre = "instagram"
    url = "https://www.instagram.com/vladzaharia/"
    weight = 2

[[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    post = "cyan"
    pre = "twitter-square"
    url = "https://twitter.com/vladzaharia/"
    weight = 3

[[menu.social]]
    identifier = "linkedin"
    name = "LinkedIn"
    post = "blue"
    pre = "linkedin"
    url = "https://www.linkedin.com/in/vladzaharia/"
    weight = 4

[[menu.social]]
    identifier = "github"
    name = "GitHub"
    post = "grey"
    pre = "github"
    url = "http://github.com/vladzaharia/"
    weight = 5
