baseurl = "https://vlad.gg/"
languageCode = "en-us"
theme = ["hugo-cloak-email", "hugo-notice", "vladgg"]
title = "Vlad Zaharia"

# Automatic menu
sectionPagesMenu = "main"

# Generate robots.txt
enableRobotsTXT = true

# Git integration
enableGitInfo = true

# Emoji integration
enableEmoji = true

# Taxonomies
[taxonomies]
  category = "categories"
  language = "languages"
  tag = "tags"
  tool = "tools"
  type = "types"

# Social networks
[[menu.social]]
    identifier = "facebook"
    name = "Facebook"
    post = "primary"
    pre = "facebook-square"
    url = "/rd/facebook"
    weight = 1

[[menu.social]]
    identifier = "instagram"
    name = "Instagram"
    post = "pink"
    pre = "instagram"
    url = "/rd/instagram"
    weight = 2

[[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    post = "cyan"
    pre = "twitter-square"
    url = "/rd/twitter"
    weight = 3

[[menu.social]]
    identifier = "linkedin"
    name = "LinkedIn"
    post = "blue"
    pre = "linkedin"
    url = "/rd/linkedin"
    weight = 4

[[menu.social]]
    identifier = "github"
    name = "GitHub"
    post = "grey"
    pre = "github"
    url = "/rd/github"
    weight = 5
