# fly.toml app configuration file generated for vladgg on 2024-09-19T22:18:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vladgg'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
