site_url: https://vlad.gg

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: projects # Used in routes, e.g., /admin/collections/blog
    label: Projects # Used in the UI
    label_singular: Project
    folder: content/projects # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: projects/{{slug}}
    filter:
      field: type
      value: project
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string
      - label: Icon
        name: icon
        widget: string
      - label: Category
        name: category
        widget: select
        options: ["Personal", "School", "Work"]
      - label: Summary
        name: summary
        widget: text
      - label: Body
        name: body
        widget: markdown
      - label: Languages
        name: languages
        widget: select
        multiple: true
        required: false
        options: ["TypeScript", "HTML", "CSS"]
      - label: Tools
        name: tools
        widget: select
        multiple: true
        required: false
        options: ["Hugo"]
      - label: Tags
        name: tags
        widget: select
        multiple: true
        required: false
        options: ["hackathon"]
      - label: Project Date
        name: date
        widget: datetime
      - label: Hidden
        name: draft
        widget: boolean
        default: true
        required: false
      - label: Type
        name: type
        widget: hidden
        default: project
  - name: pages
    label: Pages
    label_singular: Page
    files:
      - name: home
        label: Home
        file: content/_index.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Icon
            name: icon
            widget: string
          - label: Body
            name: body
            widget: markdown
          - label: Menu Weight
            name: weight
            widget: number
            default: 10
          - label: Published Date
            name: date
            widget: datetime
          - label: Hidden
            name: draft
            widget: boolean
            default: true
            required: false
          - label: Type
            name: type
            widget: hidden
            default: project
      - name: about
        label: About
        file: content/about/_index.md
        preview_path: about
        fields:
          - label: Title
            name: title
            widget: string
          - label: Icon
            name: icon
            widget: string
          - label: Body
            name: body
            widget: markdown
          - label: Menu Weight
            name: weight
            widget: number
            default: 10
          - label: Published Date
            name: date
            widget: datetime
          - label: Hidden
            name: draft
            widget: boolean
            default: true
            required: false
          - label: Type
            name: type
            widget: hidden
            default: project
      - name: projects
        label: Projects
        file: content/projects/_index.md
        preview_path: projects
        fields:
          - label: Title
            name: title
            widget: string
          - label: Icon
            name: icon
            widget: string
          - label: Body
            name: body
            widget: markdown
          - label: Menu Weight
            name: weight
            widget: number
            default: 10
          - label: Published Date
            name: date
            widget: datetime
          - label: Hidden
            name: draft
            widget: boolean
            default: true
            required: false
          - label: Type
            name: type
            widget: hidden
            default: project
      - name: contact
        label: Contact
        file: content/contact/_index.md
        preview_path: contact
        fields:
          - label: Title
            name: title
            widget: string
          - label: Icon
            name: icon
            widget: string
          - label: Body
            name: body
            widget: markdown
          - label: Menu Weight
            name: weight
            widget: number
            default: 10
          - label: Published Date
            name: date
            widget: datetime
          - label: Hidden
            name: draft
            widget: boolean
            default: true
            required: false
          - label: Type
            name: type
            widget: hidden
            default: project