# Workflow to build using Hugo

# Name of Workflow
name: HUGO

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: true  # Fetch Hugo themes
            fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # Step 2 - Sets up the latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'
            extended: true

      # Step 3 - Clean and don't fail
      - name: Clean public directory
        run: rm -rf public

      # Step 4 - Builds the site using the latest version of Hugo
      # Also specifies the theme we want to use
      - name: Build
        run: hugo

      - name: Publish to IPFS
        uses: aquiladev/ipfs-action@v0.2.2-alpha.0
        id: ipfs
        with:
          path: ./public
          host: ipfs.zhr.one
          port: 443
          protocol: https
          timeout: 180000
          key: k51qzi5uqu5dh9imz8fdkd0xh229t8nkxezvke2r3xkx3pfh54ev4hsuu27uek
